# configs/parts/1b2.yaml

part: 1b2
name: "Variational Dropout"
description: "Applying the same dropout mask at every time step in the LSTM model."
# The grid of parameters to try when testing == true
parameters:
  n_epochs: 100
  patience_value: 5
  tied_size: [300, 350, 400]
  emb_dropout: [0.1, 0.3, 0.5]
  out_dropout: [0.1, 0.3, 0.5]
  optimizer: "SGD"
  lr: [0.1, 0.5]
  clip: 5.0
  train_batch_size: 64
  eval_batch_size: 128

# The fixed parameters to use when testing == false
best_parameters:
  n_epochs: 100
  patience_value: 5
  tied_size: 400
  emb_dropout: 0.3
  out_dropout: 0.3
  optimizer: "SGD"
  lr: 0.5
  clip: 5.0
  train_batch_size: 64
  eval_batch_size: 128