# configs/parts/2b1.yaml

part: 2b1
name: "Pre-trained BERT model"
description: "Pre-trained BERT models for intent classification and slot filling"

# The grid of parameters to try when testing == true
parameters:
  n_epochs: 200
  runs: 3
  patience_value: 5
  intent_dropout: [0.1]
  slot_dropout: [0.1, 0.2]
  optimizer: "Adam"
  lr: [3e-5, 5e-5]
  clip: 5.0
  train_batch_size: 64
  eval_batch_size: 128

# The fixed parameters to use when testing == false
best_parameters:
  n_epochs: 200
  runs: 5
  patience_value: 5
  intent_dropout: 0.1
  slot_dropout: 0.2
  optimizer: "Adam"
  lr: 5e-05
  clip: 5.0
  train_batch_size: 64
  eval_batch_size: 128