# configs/parts/1a3.yaml

part: 1a3
name: "LSTM with Dropout and AdamW"
description: "Replacing the SGD optimizer with AdamW in the LSTM + Dropout model."

# The grid of parameters to try when testing == true
parameters:
  n_epochs: 100
  patience_value: 5
  hid_size: [200, 250, 300, 350, 400]
  emb_size: [300, 350, 400, 450, 500]
  emb_dropout: [0.1, 0.2, 0.3, 0.4, 0.5]
  out_dropout: [0.1, 0.2, 0.3, 0.4, 0.5]
  optimizer: "AdamW"
  lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
  clip: 5.0
  train_batch_size: 64
  eval_batch_size: 128

# The fixed parameters to use when testing == false
best_parameters:
  n_epochs: 100
  patience_value: 5
  hid_size: 500
  emb_size: 500
  emb_dropout: [0.1, 0.3, 0.5]
  out_dropout: [0.1, 0.3, 0.5]
  optimizer: "AdamW"
  lr: 0.005
  clip: 5.0
  train_batch_size: 64
  eval_batch_size: 128